//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoundryCenter.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zMenu() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoundryCenter.Localization.zMenu", typeof(zMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archiving descriptor....
        /// </summary>
        public static string FileArchiving {
            get {
                return ResourceManager.GetString("FileArchiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open....
        /// </summary>
        public static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About program....
        /// </summary>
        public static string HelpAboutProgram {
            get {
                return ResourceManager.GetString("HelpAboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tutorial.
        /// </summary>
        public static string HelpTutorial {
            get {
                return ResourceManager.GetString("HelpTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Imperial system.
        /// </summary>
        public static string MeasureUnit_Imperial {
            get {
                return ResourceManager.GetString("MeasureUnit_Imperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metric system (°C).
        /// </summary>
        public static string MeasureUnit_Metric_Celsius {
            get {
                return ResourceManager.GetString("MeasureUnit_Metric_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metric system (°K).
        /// </summary>
        public static string MeasureUnit_Metric_Kelvin {
            get {
                return ResourceManager.GetString("MeasureUnit_Metric_Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flow  simulation.
        /// </summary>
        public static string ModelApp_Flow {
            get {
                return ResourceManager.GetString("ModelApp_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flow &amp; Solid  simulation.
        /// </summary>
        public static string ModelApp_FlowSolid {
            get {
                return ResourceManager.GetString("ModelApp_FlowSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick flow  simulation.
        /// </summary>
        public static string ModelApp_QuickFlow {
            get {
                return ResourceManager.GetString("ModelApp_QuickFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Solid simulation.
        /// </summary>
        public static string ModelApp_Solid {
            get {
                return ResourceManager.GetString("ModelApp_Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore default arrangement.
        /// </summary>
        public static string OptionsClearRegister {
            get {
                return ResourceManager.GetString("OptionsClearRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string OptionsLanguage {
            get {
                return ResourceManager.GetString("OptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MeasureUnit.
        /// </summary>
        public static string OptionsMeasureUnit {
            get {
                return ResourceManager.GetString("OptionsMeasureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launches simulate module.
        /// </summary>
        public static string OptionsModelApp {
            get {
                return ResourceManager.GetString("OptionsModelApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application settings path....
        /// </summary>
        public static string OptionsPath {
            get {
                return ResourceManager.GetString("OptionsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore arrangement from previous version.
        /// </summary>
        public static string OptionsPreviousState {
            get {
                return ResourceManager.GetString("OptionsPreviousState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project management....
        /// </summary>
        public static string OptionsProject {
            get {
                return ResourceManager.GetString("OptionsProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Licensing.
        /// </summary>
        public static string RemoteAssistance {
            get {
                return ResourceManager.GetString("RemoteAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply v2c file.
        /// </summary>
        public static string RemoteAssistanceApplyV2C {
            get {
                return ResourceManager.GetString("RemoteAssistanceApplyV2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home page....
        /// </summary>
        public static string RemoteAssistanceHomePage {
            get {
                return ResourceManager.GetString("RemoteAssistanceHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On-line support....
        /// </summary>
        public static string RemoteAssistanceOnLineSupport {
            get {
                return ResourceManager.GetString("RemoteAssistanceOnLineSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Support....
        /// </summary>
        public static string RemoteAssistanceSupport {
            get {
                return ResourceManager.GetString("RemoteAssistanceSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create c2v file.
        /// </summary>
        public static string RemoteAssistanceWriteC2V {
            get {
                return ResourceManager.GetString("RemoteAssistanceWriteC2V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Button style.
        /// </summary>
        public static string ToolsButtonStyle {
            get {
                return ResourceManager.GetString("ToolsButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Big image.
        /// </summary>
        public static string ToolsButtonStyleBigImage {
            get {
                return ResourceManager.GetString("ToolsButtonStyleBigImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Small image.
        /// </summary>
        public static string ToolsButtonStyleSmallImage {
            get {
                return ResourceManager.GetString("ToolsButtonStyleSmallImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text only.
        /// </summary>
        public static string ToolsButtonStyleText {
            get {
                return ResourceManager.GetString("ToolsButtonStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show/Hide command....
        /// </summary>
        public static string ToolsCommandList {
            get {
                return ResourceManager.GetString("ToolsCommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run.
        /// </summary>
        public static string ToolsRun {
            get {
                return ResourceManager.GetString("ToolsRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External tools....
        /// </summary>
        public static string ToolsUserTools {
            get {
                return ResourceManager.GetString("ToolsUserTools", resourceCulture);
            }
        }
    }
}
