//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoundryCenter.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zText() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoundryCenter.Localization.zText", typeof(zText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link date :.
        /// </summary>
        public static string AppLinkDate {
            get {
                return ResourceManager.GetString("AppLinkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на release.
        /// </summary>
        public static string AppRelease {
            get {
                return ResourceManager.GetString("AppRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version :.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string CloseApp {
            get {
                return ResourceManager.GetString("CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning: This computer program is protected by copyright law and international treates. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law..
        /// </summary>
        public static string DlgAboutLicense {
            get {
                return ResourceManager.GetString("DlgAboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Professional system of computer simulation of thermal and hydrodynamic processes in foundry.
        /// </summary>
        public static string DlgAboutSoftware {
            get {
                return ResourceManager.GetString("DlgAboutSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string DlgAboutTitle {
            get {
                return ResourceManager.GetString("DlgAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show/Hide command .
        /// </summary>
        public static string DlgCommandListTitle {
            get {
                return ResourceManager.GetString("DlgCommandListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer To Vendor Files (*.c2v)|*.c2v|All Files (*.*)|*.*.
        /// </summary>
        public static string DlgCreateC2VFilter {
            get {
                return ResourceManager.GetString("DlgCreateC2VFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Generated Status Information As.
        /// </summary>
        public static string DlgCreateC2VTitle {
            get {
                return ResourceManager.GetString("DlgCreateC2VTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute files|*.exe|All Files|*.*.
        /// </summary>
        public static string DlgExternalToolsFilter {
            get {
                return ResourceManager.GetString("DlgExternalToolsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External tools path.
        /// </summary>
        public static string DlgExternalToolsTitle {
            get {
                return ResourceManager.GetString("DlgExternalToolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Casting file.
        /// </summary>
        public static string DlgFileArchivingCVG {
            get {
                return ResourceManager.GetString("DlgFileArchivingCVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Material database.
        /// </summary>
        public static string DlgFileArchivingDatabase {
            get {
                return ResourceManager.GetString("DlgFileArchivingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Descriptor path.
        /// </summary>
        public static string DlgFileArchivingDescriptor {
            get {
                return ResourceManager.GetString("DlgFileArchivingDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archiving descriptor.
        /// </summary>
        public static string DlgFileArchivingTitle {
            get {
                return ResourceManager.GetString("DlgFileArchivingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location ZIP file.
        /// </summary>
        public static string DlgFileArchivingZip {
            get {
                return ResourceManager.GetString("DlgFileArchivingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vendor To Customer Files (*.v2c)|*.v2c|All Files (*.*)|*.*.
        /// </summary>
        public static string DlgOpenV2CFilter {
            get {
                return ResourceManager.GetString("DlgOpenV2CFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open HASP Update File.
        /// </summary>
        public static string DlgOpenV2CTitle {
            get {
                return ResourceManager.GetString("DlgOpenV2CTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings location:.
        /// </summary>
        public static string DlgOptionsLocation {
            get {
                return ResourceManager.GetString("DlgOptionsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application settings path.
        /// </summary>
        public static string DlgOptionsTitle {
            get {
                return ResourceManager.GetString("DlgOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3D geometry location:.
        /// </summary>
        public static string DlgProject3DGeometry {
            get {
                return ResourceManager.GetString("DlgProject3DGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clean project.
        /// </summary>
        public static string DlgProjectClear {
            get {
                return ResourceManager.GetString("DlgProjectClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current project:.
        /// </summary>
        public static string DlgProjectCurrent {
            get {
                return ResourceManager.GetString("DlgProjectCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Projects location:.
        /// </summary>
        public static string DlgProjectLocation {
            get {
                return ResourceManager.GetString("DlgProjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New project.
        /// </summary>
        public static string DlgProjectNew {
            get {
                return ResourceManager.GetString("DlgProjectNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Projects management.
        /// </summary>
        public static string DlgProjectTitle {
            get {
                return ResourceManager.GetString("DlgProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External Tools.
        /// </summary>
        public static string DlgUserToolsListTitle {
            get {
                return ResourceManager.GetString("DlgUserToolsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CAD files (*.stl,*.flt)|*.stl;*.flt|STEP files(*.step,*.stp)|*.step;*.stp|CVgeo files (*.cvg)|*.cvg|Simulation files (*.sim)|*.sim|Descriptor files (*.psp)|*.psp|All files (*.*)|*.*.
        /// </summary>
        public static string FileOpenFilter {
            get {
                return ResourceManager.GetString("FileOpenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CAD files (*.stl,*.flt)|*.stl;*.flt|STEP files(*.step,*.stp)|*.step;*.stp|CVgeo files (*.cvg)|*.cvg|Simulation files (*.sim)|*.sim|Descriptor files (*.psp)|*.psp|All files (*.*)|*.*.
        /// </summary>
        public static string FileOpenFilterCamito {
            get {
                return ResourceManager.GetString("FileOpenFilterCamito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CVgeo files (*.cvg)|*.cvg|All files (*.*)|*.*.
        /// </summary>
        public static string FileOpenFilterCVgeo {
            get {
                return ResourceManager.GetString("FileOpenFilterCVgeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data files (*.mdb,*.sdf)|*.mdb;*.sdf|All Files (*.*)|*.*.
        /// </summary>
        public static string FileOpenFilterDatabase {
            get {
                return ResourceManager.GetString("FileOpenFilterDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CAD files (*.stl,*.flt)|*.stl;*.flt|STEP files(*.step,*.stp)|*.step;*.stp|Demo CVgeo files (*.cvgdemo)|*.cvgdemo|Demo simulation files (*.simdemo)|*.simdemo|Descriptor files (*.psp)|*.psp|All files (*.*)|*.*.
        /// </summary>
        public static string FileOpenFilterDemo {
            get {
                return ResourceManager.GetString("FileOpenFilterDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AppSettings files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        public static string FileOpenFilterXml {
            get {
                return ResourceManager.GetString("FileOpenFilterXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zip files (*.zip)|*.zip|All files (*.*)|*.*.
        /// </summary>
        public static string FileOpenFilterZip {
            get {
                return ResourceManager.GetString("FileOpenFilterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Foundry Center.
        /// </summary>
        public static string FoundryCenterTitle {
            get {
                return ResourceManager.GetString("FoundryCenterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select language :.
        /// </summary>
        public static string LanguageBox {
            get {
                return ResourceManager.GetString("LanguageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License date : .
        /// </summary>
        public static string LicenceDate {
            get {
                return ResourceManager.GetString("LicenceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License holder :.
        /// </summary>
        public static string LicenceHolder {
            get {
                return ResourceManager.GetString("LicenceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Isn&apos;t defined.
        /// </summary>
        public static string LicenceNoSet {
            get {
                return ResourceManager.GetString("LicenceNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License number : .
        /// </summary>
        public static string LicenceNumber {
            get {
                return ResourceManager.GetString("LicenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlimited.
        /// </summary>
        public static string LicenceUnlimited {
            get {
                return ResourceManager.GetString("LicenceUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Imperial system.
        /// </summary>
        public static string MeasureUnit_Imperial {
            get {
                return ResourceManager.GetString("MeasureUnit_Imperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metric system (°C).
        /// </summary>
        public static string MeasureUnit_Metric_Celsius {
            get {
                return ResourceManager.GetString("MeasureUnit_Metric_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metric system (°K).
        /// </summary>
        public static string MeasureUnit_Metric_Kelvin {
            get {
                return ResourceManager.GetString("MeasureUnit_Metric_Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select measure units:.
        /// </summary>
        public static string MeasureUnitBox {
            get {
                return ResourceManager.GetString("MeasureUnitBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser.
        /// </summary>
        public static string ModulusBrowse {
            get {
                return ResourceManager.GetString("ModulusBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calibrate.
        /// </summary>
        public static string ModulusCalibrate {
            get {
                return ResourceManager.GetString("ModulusCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database.
        /// </summary>
        public static string ModulusDatabase {
            get {
                return ResourceManager.GetString("ModulusDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default settings.
        /// </summary>
        public static string ModulusDefault {
            get {
                return ResourceManager.GetString("ModulusDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flow simulation.
        /// </summary>
        public static string ModulusFlow {
            get {
                return ResourceManager.GetString("ModulusFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flow &amp; Solid.
        /// </summary>
        public static string ModulusFlowSolid {
            get {
                return ResourceManager.GetString("ModulusFlowSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Good Guys&apos; Index.
        /// </summary>
        public static string ModulusGoodGuysIndex {
            get {
                return ResourceManager.GetString("ModulusGoodGuysIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3D Import.
        /// </summary>
        public static string ModulusImport3D {
            get {
                return ResourceManager.GetString("ModulusImport3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simulation setup.
        /// </summary>
        public static string ModulusInitial {
            get {
                return ResourceManager.GetString("ModulusInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NovaMethod.
        /// </summary>
        public static string ModulusNovaMethod {
            get {
                return ResourceManager.GetString("ModulusNovaMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NovaShot.
        /// </summary>
        public static string ModulusPQdiagram {
            get {
                return ResourceManager.GetString("ModulusPQdiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick flow simulation.
        /// </summary>
        public static string ModulusQuickFlow {
            get {
                return ResourceManager.GetString("ModulusQuickFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Solidification.
        /// </summary>
        public static string ModulusSolid {
            get {
                return ResourceManager.GetString("ModulusSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NovaStress.
        /// </summary>
        public static string ModulusStress {
            get {
                return ResourceManager.GetString("ModulusStress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [New external tool].
        /// </summary>
        public static string NewExternalTool {
            get {
                return ResourceManager.GetString("NewExternalTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        public static string OptionsImportFilter {
            get {
                return ResourceManager.GetString("OptionsImportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LVMFlow.
        /// </summary>
        public static string ProductNameLVM {
            get {
                return ResourceManager.GetString("ProductNameLVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NovaFlow&amp;Solid.
        /// </summary>
        public static string ProductNameNFS {
            get {
                return ResourceManager.GetString("ProductNameNFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NovaOne Gravity.
        /// </summary>
        public static string ProductNameNFS_GRAVITY_LIGHT {
            get {
                return ResourceManager.GetString("ProductNameNFS_GRAVITY_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NovaOne HPD.
        /// </summary>
        public static string ProductNameNFS_HPD_LIGHT {
            get {
                return ResourceManager.GetString("ProductNameNFS_HPD_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External Tools.
        /// </summary>
        public static string UserButtonPanel {
            get {
                return ResourceManager.GetString("UserButtonPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument.
        /// </summary>
        public static string UserToolsArgument {
            get {
                return ResourceManager.GetString("UserToolsArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command.
        /// </summary>
        public static string UserToolsCommand {
            get {
                return ResourceManager.GetString("UserToolsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string UserToolsTitle {
            get {
                return ResourceManager.GetString("UserToolsTitle", resourceCulture);
            }
        }
    }
}
